name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        # ক্যাশ ম্যানেজমেন্টের জন্য তারিখ সেভ করা
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Buildozer Cache
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          # আপনার প্রজেক্টের জন্য অটোমেটিক কমান্ড রান করবে
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: BDCS-WiFi-Brute-APK
          path: bin/*.apk
